### ISSUE TITLE
Create Control (Arduino)

### ISSUE THREAD

**Issue by ryanvade** [SIUE-ARC/ARCBOT#2]
The create module should have the following overall capability

- [x] Drive
- [x] Turn
- [ ] Access IR Sensors
- [x] Run Demos
- [ ] Read Battery Information
- [x] Read Bumper Sensors

**Comment by BryanOrabutt** [comment]
The following create commands still need tested:

query_sensor()
wait_time()
wait_distance()
wait_angle()
wait_event()

All functions described in hardware.h need to be tested. Function ir_sensor() needs to be implemented.
